<?php
/**
 * dbconn.inc :: The Database string constants
 *
 * @package dbdMVC
 * @version 1.2
 * @author Will Mason <will@dontblinkdesign.com>
 * @copyright Copyright (c) 2009 by Don't Blink Design
 */
/**
 * Constant boolean to flag file inclusion.
 */
define('DBCONN_INCLUDED', true);

/**
 * Constant default database name if none is specified at connection time
 */
define('DBCONN_DEFAULT_DB', '');

/**
 * Database connection strings
 */
define('DB_DRIVER', 'mysql');
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_USER', 'dbdmvc');
define('DB_PASS', 'i$th3$hit');
