#!/bin/bash

echo "USAGE: ${0} [user]"

if [ $USER != "root" ]
then
        echo "TRY: sudo ${0} ${@}"
        exit 1
fi

if [ ${#} -gt 0 ]
then
	u=${1}

	echo "Changing ownership to ${u}"
	chown -R ${u}:svn ./
fi

chmod 775 `find ./ -type d`

echo "Changing files to 0664"
chmod 664 `find ./ -type f | grep -v "${0}"`

echo "Fixing special files & dirs"
chmod 775 ./clearCaches
chmod 775 ./dbdApp/dbdcli
#chmod 777 ./dbdApp/cache
#chmod 777 ./httpdocs/images/cache
#chmod 777 ./dbdApp/views/.templates_c

echo "Done..."
